/*Relatório de departamentos */
SELECT *FROM DEPARTAMENTO

/*RELATORIO DE DEPENDENTE*/
SELECT *FROM DEPENDENTE
SELECT  *FROM COLABORADOR


SELECT   COL.NOME AS COLABORADOR, DEP.NOME AS DEPENDENTE, DEP.DATA_NASCIMENTO , DEP.PARENTESCO
FROM DEPENDENTE  AS DEP
INNER JOIN COLABORADOR AS COL ON COL.MATRICULA  = DEP.MATRICULA_COLABORADOR
ORDER BY  COL.NOME,DEP.NOME

/* Inserir novo colaborador em projeto */
SELECT *FROM PAPEL	
INSERT INTO PAPEL (NOME) VALUE('ESPECIALISTADE NEGOCIOS')

SELECT *FROM PROJETO
INSERT INTO PROJETO (NOME, INICIO, FIM , ID_RESPONSAVEL) VALUES  ('BI','23-08-06','31-12-06','123')
SELECT *FROM  COLABORADOR

SELECT *FROM DEPARTAMENTO
INSERT INTO DEPARTAMENTO (SIGLA, NOME) VALUES ('DIR', 'DIRETORIA');

/*INSERINDO DADOS DO FUNCIONARIO*/
INSERT INTO COLABORADOR  (MATRICULA, CPF, SALARIO, SIGLA_DEP, NOME)VALUES('321', '092555',1.500,'DIR', 'FULANDO DE TAL')

/*INSERINDO ENDERECO DO FUNCIONARIO */
SELECT *FROM ENDERECO
INSERT  INTO ENDERECO (LOGRADOURO, BAIRRO, CIDADE, ESTADO, COMPLEMENTO, CEP, MATRICULA_COLABORADOR) VALUES 
('RUA SAO PAULO,1120','CENTRO', 'FRANCISCO BELTRAO', 'PARANA', 'LOJA DE ROUPAS', '85601010' , '321')
/*INSERINDO DADOS DE CONTATO DO FUNCIONARIO*/
SELECT *FROM CONTATO_COLABORADOR
INSERT  INTO CONTATO_COLABORADOR (TELEFONE_1 , TELEFONE_2 , EMAIL_CORPORATIVO, EMAIL_PESSOAL, MATRICULA_COLABORADOR) VALUES
('(61)99999-9999', '(61)999-999999','FULANOTAL','FULANOTAL@COPOR', '321')

/*INSERINDO FUNCIONARIO NO PROJETO*/
SELECT *FROM ATUACAO_PROJETO
INSERT INTO ATUACAO_PROJETO (MATRICULA_COLABORADOR, ID_PROJETO, ID_PAPEL) VALUES ('321', '2','3')

/*Excluir departamento SECAP  e todos os colaboradores*/
SELECT *FROM COLABORADOR
SELECT *FROM DEPARTAMENTO
INSERT INTO DEPARTAMENTO (SIGLA, NOME) VALUES ('SECAP', 'SECAP');
INSERT INTO COLABORADOR  (MATRICULA, CPF, SALARIO, SIGLA_DEP, NOME)VALUES('321', '092555',1.500,'SECAP', 'DOUGLAS');
INSERT INTO COLABORADOR  (MATRICULA, CPF, SALARIO, SIGLA_DEP, NOME)VALUES('1', '092555',1.500,'SECAP', 'MATEUS');
INSERT INTO COLABORADOR  (MATRICULA, CPF, SALARIO, SIGLA_DEP, NOME)VALUES('2', '092555',1.500,'SECAP', 'MARCOS');

/*DELETANDO COLABORADORES*/
DELETE 
FROM   colaborador
WHERE SIGLA_DEP = 'SECAP'
/*DELETANDO DEPARTAMENTO*/
DELETE 
FROM DEPARTAMENTO
WHERE SIGLA = 'SECAP'



============
/* Relatório de departamentos- Banco Pronto*/

select sigla , nome
 from departamento 
 order by nome
 
