


--1. Criar procedure insere_projeto
CREATE OR REPLACE PROCEDURE BRH.INSERE_PROJETO 
(  
    p_NOME IN BRH.PROJETO.NOME%TYPE,
    P_RESPONSAVEL IN BRH.PROJETO.RESPONSAVEL%TYPE,
    p_DATA_CRIACAO IN PROJETO.INICIO%TYPE
)
IS 
BEGIN
 insert into projeto (nome, RESPONSAVEL, INICIO) VALUES (p_NOME, P_RESPONSAVEL , p_DATA_CRIACAO);

END;

EXECUTE BRH.INSERE_PROJETO('PROGRAMADO JavaScript','Z123', Sysdate)

--2. Criar função calcula_idade
select *from brh.colaborador;

CREATE OR REPLACE FUNCTION brh.CALC_IDADE (
      p_IDADE IN DATE)
return FLOAT
IS
BEGIN 
RETURN FLOOR(MONTHS_BETWEEN(SYSDATE, p_IDADE)/12);
END;

SELECT BRH.CALC_IDADE (TO_DATE('06/09/2010' , 'DD/MM/YYYY')) AS IDADE FROM DUAL;




/*FINALIZA PROJETO*/

CREATE OR REPLACE FUNCTION BRH.FINALIZAR_PROJETO (
 p_ID IN BRH.PROJETO.ID%TYPE)
 RETURN  BRH.PROJETO.FIM%TYPE
 IS 
      p_FINALIZACAO BRH.PROJETO.FIM%TYPE;
 BEGIN
  p_FINALIZACAO:= SYSDATE;
 UPDATE BRH.PROJETO SET FIM = p_FINALIZACAO WHERE ID = p_ID;
 RETURN p_FINALIZACAO;
 END;
 
 
 select *from brh.projeto;
 
 variable data_fim varchar2(10);
 EXECUTE :data_fim := BRH.FINALIZA_PROJETO(6);
 PRINT data_fim;